// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpdatedDojoDatchi.Models;

namespace UpdatedDojoDatchi.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20181210165030_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UpdatedDojoDatchi.Models.MonsterObject", b =>
                {
                    b.Property<int>("MonsterObjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Energy");

                    b.Property<int>("Fullness");

                    b.Property<int>("Happiness");

                    b.Property<int>("Meals");

                    b.Property<string>("Reaction");

                    b.Property<bool>("isAlive");

                    b.HasKey("MonsterObjectId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("UpdatedLogReg.Models.UserObject", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("MonsterObjectId");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.HasIndex("MonsterObjectId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UpdatedLogReg.Models.UserObject", b =>
                {
                    b.HasOne("UpdatedDojoDatchi.Models.MonsterObject", "UserMonster")
                        .WithMany()
                        .HasForeignKey("MonsterObjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
